[build]
target = "mipsel-unknown-none"

[target.mipsel-unknown-none]
rustflags = [
    "-C", "force-frame-pointers=yes",
    "-C", "llvm-args=--debugger-tune=gdb",
]

[unstable]
build-std = ["core", "compiler_builtins"]
